---
title: "final"
author: "Sibei Liu"
date: "2019/12/3"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,message = FALSE,warning = FALSE)
```

## table1
```{r}
library(tidyverse)
library(arsenal)
library(knitr)
require(survival)
data_0=read_csv("Lawsuit.csv") %>% 
  janitor::clean_names()
data=data_0 %>% mutate(
  total_sal=sal94+sal95,
  mean_sal=total_sal/2
) %>% 
  select(-sal94,-sal95,-total_sal)
  
```

```{r}
my_labels2 <- list(dept = "Dept,n%", clin="Clin n%", cert="Cert,n%",prate="Publication rate",exper="Years since obtaining MD",
                   mean_sal="Salary",rank="Rank,n%")

 my_controls <- tableby.control(total = T,
  test=T,  
  digits=4,
  numeric.stats = c("meansd", "medianq1q3"),
  cat.stats = c("countpct"),
  stats.labels = list(
    meansd ="Mean (SD)",
    medianq1q3 = "Median (Q1, Q3)",
    countpct = "N (%)"))
```

```{r}
data_1<-data %>% 
  mutate(dept=factor(dept, labels=c("Molecular Biology","Physiology","Genetics","Pediatrics","Medicine","Surgery")),
         gender=factor(gender, labels=c("Female","Male")),
         clin=factor(clin, labels=c("Primarily research emphasis","Primarily clinical emphasis")),
         cert=factor(cert, labels=c("not certified", "Board certified")),
         rank=factor(rank,label=c("Assistant","Associate","Full professor"))
         )
```


```{r}

table <- tableby(gender ~ dept + clin+ cert + prate+exper+rank+mean_sal, data=data_1,control=my_controls)
c=summary(table, title = "Table1:Descriptive statistics for by Gender and Test", labelTranslations = my_labels2, text=T)
knitr::kable(c)
```

## distribution of y

```{r}
ggplot(data_1,aes(x=mean_sal))+geom_histogram(aes(y=..density..)) + geom_density(col = "black",alpha=0)
```
not normal

```{r}
library(HH)
data_2=data_1 %>% 
  mutate(
    log_sal=log(mean_sal)
  )
  ggplot(data_2,aes(x=log_sal))+geom_histogram(aes(y=..density..)) + geom_density(col = "black",alpha=0)
data_2=data_2 %>% 
    dplyr::select(-id,-mean_sal)
```

seems normal

```{r}
# stepwise
muli1=lm(log_sal~.,data=data_2)
step(muli1) %>% 
  summary()
```

```{r}
muli2=lm(formula = log_sal ~ gender + dept + clin + cert + prate + exper + rank, 
    data = data_2)
summary(muli2)
muli3=lm(formula = log_sal ~ gender + dept + clin + cert + exper + rank, 
    data = data_2)
summary(muli3)
(0.025763-0.019536)/0.019536
```

```{r}
# foreward
full_model = lm(log_sal ~ . ,data = data_2)
step_null <- lm(log_sal ~1, data = data_2)
for_model <- step(step_null, scope = list(lower = step_null, upper = full_model), direction = "forward")
```

```{r}
# interaction
interact_lm=lm(log_sal ~ gender*dept*clin*cert*exper*rank, data=data_2)
summary(interact_lm)
```

```{r}
# colinearity
library(rms)
vif(muli1)
```

```{r}
# correlation
pairs(data_2)
# normality
library(DataExplorer)
plot_qq(data_2)
# categorical
plot_bar(data_2, maxcat = 20, parallel = TRUE)
```
